name: Build and Test

on: [push]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: npm install, build, and test
    - run: npm install
    - run: npm run build
    - run: npm run test
